'use strict'

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Items', [
      {
        id: 1,
        name: 'Bravčový plátok',
        price: 87,
        detail: 'Steak z výbrerového bravčového mäsa',
        allergens: '1,2,3',
        grammage: 150,
        volume: null,
        alcohol: null,
        itemCategoryId: 1,
        menuId: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 2,
        name: 'Kurací plátok',
        price: 69,
        detail: 'Plátok kuracieho mäsa z domáceho chovu',
        allergens: '1,2,3',
        grammage: 150,
        volume: null,
        alcohol: null,
        itemCategoryId: 1,
        menuId: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 3,
        name: 'Hovadzí platok',
        price: 95,
        detail: 'Steak z prvotriedneho hovädzieho mäsa',
        allergens: '1,2,3',
        grammage: 150,
        volume: null,
        alcohol: null,
        itemCategoryId: 1,
        menuId: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 4,
        name: 'Ryža',
        price: 49,
        detail: 'Celozrnná ryža',
        allergens: '3',
        grammage: 100,
        volume: null,
        alcohol: null,
        itemCategoryId: 2,
        menuId: 2,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 5,
        name: 'Zemiaky',
        price: 49,
        detail: 'Krájané zemiaky',
        allergens: '3',
        grammage: 100,
        volume: null,
        alcohol: null,
        itemCategoryId: 2,
        menuId: 2,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 6,
        name: 'Hranolky',
        price: 49,
        detail: 'Smažené hranolky',
        allergens: '3',
        grammage: 100,
        volume: null,
        alcohol: null,
        itemCategoryId: 2,
        menuId: 2,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 7,
        name: 'Cola',
        price: 30,
        detail: 'Je to cola',
        allergens: '',
        grammage: null,
        volume: 0.5,
        alcohol: 0,
        itemCategoryId: 4,
        menuId: 3,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 8,
        name: 'Radler',
        price: 30,
        detail: 'pivo',
        allergens: '',
        grammage: null,
        volume: 0.5,
        alcohol: 0,
        itemCategoryId: 4,
        menuId: 3,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 9,
        name: 'Minerálka',
        price: 30,
        detail: 'Je to cola',
        allergens: '',
        grammage: null,
        volume: 0.3,
        alcohol: 0,
        itemCategoryId: 4,
        menuId: 3,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 10,
        name: 'Jack',
        price: 59,
        detail: ' ',
        allergens: '',
        grammage: null,
        volume: 0.04,
        alcohol: 0.4,
        itemCategoryId: 4,
        menuId: 4,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 11,
        name: 'Vodka',
        price: 49,
        detail: ' ',
        allergens: '',
        grammage: null,
        volume: 0.04,
        alcohol: 0.4,
        itemCategoryId: 4,
        menuId: 4,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 12,
        name: 'Sôja',
        price: 62,
        detail: 'Sója so zeleninovou oblohou',
        allergens: '6,7',
        grammage: 120,
        volume: null,
        alcohol: null,
        itemCategoryId: 4,
        menuId: 5,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 13,
        name: 'Zeleninová misa',
        price: 69,
        detail: 'Zeleninový šalát',
        allergens: '',
        grammage: 120,
        volume: null,
        alcohol: 0,
        itemCategoryId: 6,
        menuId: 5,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 14,
        name: 'Brandenburg special',
        price: 54,
        detail: 'Červené víno',
        allergens: '6',
        grammage: null,
        volume: 0.2,
        alcohol: 0.18,
        itemCategoryId: 3,
        menuId: 6,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 15,
        name: 'Tuscana private',
        price: 58,
        detail: 'Biele víno',
        allergens: '6',
        grammage: null,
        volume: 0.2,
        alcohol: 0.18,
        itemCategoryId: 3,
        menuId: 6,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 16,
        name: 'Pilsner Urquel',
        price: 40,
        detail: 'Špecialita 12 stupnov',
        allergens: '6',
        grammage: null,
        volume: 0.5,
        alcohol: 0.06,
        itemCategoryId: 3,
        menuId: 7,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 17,
        name: 'Gambrinus',
        price: 30,
        detail: 'Špecialita 11 stupnov',
        allergens: '6',
        grammage: null,
        volume: 0.5,
        alcohol: 0.06,
        itemCategoryId: 3,
        menuId: 7,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 19,
        name: 'Chipsy bohemia',
        price: 46,
        detail: 'Solené, paprikové, wasaby',
        allergens: '6',
        grammage: 100,
        volume: null,
        alcohol: null,
        itemCategoryId: 7,
        menuId: 8,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        id: 20,
        name: 'Tyčinky',
        price: 45,
        detail: 'Solené',
        allergens: '6',
        grammage: 50,
        volume: null,
        alcohol: null,
        itemCategoryId: 7,
        menuId: 8,
        createdAt: new Date(),
        updatedAt: new Date()
      }
    ])
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Items', null, {})
  }
}
